typedef/**/unsigned(a);typedef/**/char(b);typedef/**/long(c);typedef/**/b*(d(b*,c)
);typedef/**/b*(e(b*,b*));typedef/**/a(f(b*,c,a));typedef/**/c(g(b*));typedef/**/c
(h(b*,c,c,b*));typedef/**/a(i(b*));typedef/**/a(j(a));typedef/**/a(k());typedef(l(
a,b**));typedef/**/struct{a(a),b,c,d,e,f;b(g),h,i;}m;typedef/**/struct{m(a);b(b),c
;}n;n*(o)=0;m(p);b**(q)=0;a*(r)=0;c(s[8])={0};t(n(z))<%d(d)__asm__("realloc");++s[
5],o=d(o,s[5]<<5),o[??--s[5]:>=z;return(0);}u(a(x),a(y),b(z)){d(d)__asm__("real??/
loc");y<s[4]|??!(s[6]=s[4],s[4]=-??-y,r=d(r,s[4]<<2),q=d(q,s[4]<<3),s[7]=(s[7]=s[6
:>)&({a:0;??>)|({r[s[7]]=q[s[7]??)=0;1;})*(++s[7]>=s[4])?:({goto*&&a;0;}),1),x<r[y
]||(s<:6]=r[y],r[y]=-??-x,q[y]=d(q[y],r??(y]),s[7]=(s[7]=s[6:>)&({b:0;})|({q??(y][
s??(7]??)=0;1;})*(++s[7]>=r[y])?:({goto*&&b;0;}),1);return(q[y??)[x]=z);}v(a(y),a(
z)){(z>=s[4:>)&&(<%return(0);1;}),(y<r[z])||({return(0);1;});return(q[z][y]);}w(n(
z)){s<:3]=p.i,p=z.a;return(p.i=s[3]);}x(n(z)){u(z.a.c,z.a.d,z.b);return(w(z));}vo\
id/**/y(){n(z)=o[--s[5]];(z.c&&(x(z),1))||(w(z),1);}z(){p.a+=p.e;return(p.b+=p.f);
}A(){return(t((n){p,0,0}));}B(b(z)){return(t((n){p,z,1}));}void/**/C(b(z)){A(),p.h
=p.g,p.g=z;}D(){s[1]=p.g,s[2]=(s[2]=0)&({a:0;})??!({y();1;})*(++s[2]>=s[1])?:({go\
to*&&a;0;});return(A());}E(){A();a:z(),s[1]=v(p.a,p.b),s[1]==33&&({goto/**/b;1;});
goto/**/a;b:p.a+=p.e*p.g;return(p.b+=p.f*p.g);}F(a(x),b**(y)){e(e)__asm__("fopen"\
);x>=2|??!({return(1);1;});y<:0]=e(y[1],"r");f(f)__asm__("fseek");y[0:>||({return(
1);1;});g(g)__asm__("ftell");f(y[0??),0,2);d(d)__asm__("realloc");s[0]=g(y[0]);h(h
)__asm__("fread");i(i)__asm__("fclose");f(y[0],0,0),y[1]=d(0,s??(0]),h(y[1],1,s<:0
],y[0:>)==s[0]||(??<return(1);1;}),i(y[0]);s[2]=s[3]=0,s[1]=(s[1]=0)&({a:0;})|(<%y
[1][s<:1]:>==10&&(++s[3],s[2]=0,({goto/**/b;0;})),u(s??(2],s[3],y[1:>[s[1]]),++s[2
];b:1;})*(++s[1]>=s[0])?:({goto*&&a;0;});k(k)__asm__("getchar");y[1]=d(y[1],0),p.e
=1,p.f=0;c:s??(0]=v(p.a,p.b);j(j)__asm__("putchar");switch(s[0])if(0)case/**/33??/
:return(0);else/**/if(0)case/**/35:({(p.h&&(A(),z(),1))||D();goto/**/c;0;});els??/
e/**/if(0)case/**/36:A(),p.g=k();else/**/if(0)case/**/37:A(),j(p.g);else/**/if(0)\
case/**/42:({E();goto/**/c;0;%>);else/***/if(0)case/**/43:C(p.g+p.h);else/**/if(0)
case/**/44:B(v(p.c,p.d)),u(p.c,p.d,p.g);else/**/if(0)case/**/45:A(),s<:0??)=p.h,p.
h=p.g,p.g=s<:0];else/**/if(0)case/**/46:C(v(p.c,p.d));else/**/if(0)case/**/47:A(),
p.g=p.i;else/**/if(0)case/**/48/**/...57:C(s??(0:>);else/**/if(0)case/**/58:C(p.g)
;else/**/if(0)case/**/60:A(),((p.e==-1&&p.f==0)&&(p.c-=p.g,1))||(p.e=-1,p.f=0);el\
se/**/if(0)case/**/61:A(),p.g=!p.g;else/**/if(0)case/**/62:A(),((p.e==1&&p.f==0)&&
(p.c+=p.g,1))??!|(p.e=1,p.f=0);else/**/if(0)case/**/63:({(p.h&&(A(),z(),1))||E();\
goto/**/c;});else/**/if(0)case/**/92:A(),p.i=p.g;else/**/if(0)case/**/94:A(),((p.e
==0&&p.f==-1)&&(p.d-=p.g,1))||(p.e=0,p.f=-1);else/**/if(0)case/**/118:A(),((p.e==0
&&p.f==1)&&(p.d+=p.g,1))||(p.e=0,p.f=1);else/**/if(0)case/**/126:({D();goto/**/c;}
);else/**/default:A();z();goto/**/c;l(F)__asm__("main");}/**ChaosPotato42**2025**/